package com.stytch.java.b2b.models.scim

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.Instant

@JsonClass(generateAdapter = true)
public data class Address
    @JvmOverloads
    constructor(
        @Json(name = "formatted")
        val formatted: String,
        @Json(name = "street_address")
        val streetAddress: String,
        @Json(name = "locality")
        val locality: String,
        @Json(name = "region")
        val region: String,
        @Json(name = "postal_code")
        val postalCode: String,
        @Json(name = "country")
        val country: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class Email
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class EnterpriseExtension
    @JvmOverloads
    constructor(
        @Json(name = "employee_number")
        val employeeNumber: String,
        @Json(name = "cost_center")
        val costCenter: String,
        @Json(name = "division")
        val division: String,
        @Json(name = "department")
        val department: String,
        @Json(name = "organization")
        val organization: String,
        @Json(name = "manager")
        val manager: Manager? = null,
    )

@JsonClass(generateAdapter = true)
public data class Entitlement
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class Group
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "display")
        val display: String,
    )

@JsonClass(generateAdapter = true)
public data class IMs
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class Manager
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "ref")
        val ref: String,
        @Json(name = "display_name")
        val displayName: String,
    )

@JsonClass(generateAdapter = true)
public data class Name
    @JvmOverloads
    constructor(
        @Json(name = "formatted")
        val formatted: String,
        @Json(name = "family_name")
        val familyName: String,
        @Json(name = "given_name")
        val givenName: String,
        @Json(name = "middle_name")
        val middleName: String,
        @Json(name = "honorific_prefix")
        val honorificPrefix: String,
        @Json(name = "honorific_suffix")
        val honorificSuffix: String,
    )

@JsonClass(generateAdapter = true)
public data class PhoneNumber
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class Photo
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class Role
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )

@JsonClass(generateAdapter = true)
public data class SCIMAttributes
    @JvmOverloads
    constructor(
        @Json(name = "user_name")
        val userName: String,
        @Json(name = "id")
        val id: String,
        @Json(name = "external_id")
        val externalId: String,
        @Json(name = "active")
        val active: Boolean,
        @Json(name = "groups")
        val groups: List<Group>,
        @Json(name = "display_name")
        val displayName: String,
        @Json(name = "nick_name")
        val nickName: String,
        @Json(name = "profile_url")
        val profileURL: String,
        @Json(name = "user_type")
        val userType: String,
        @Json(name = "title")
        val title: String,
        @Json(name = "preferred_language")
        val preferredLanguage: String,
        @Json(name = "locale")
        val locale: String,
        @Json(name = "timezone")
        val timezone: String,
        @Json(name = "emails")
        val emails: List<Email>,
        @Json(name = "phone_numbers")
        val phoneNumbers: List<PhoneNumber>,
        @Json(name = "addresses")
        val addresses: List<Address>,
        @Json(name = "ims")
        val ims: List<IMs>,
        @Json(name = "photos")
        val photos: List<Photo>,
        @Json(name = "entitlements")
        val entitlements: List<Entitlement>,
        @Json(name = "roles")
        val roles: List<Role>,
        @Json(name = "x509certificates")
        val x509Certificates: List<X509Certificate>,
        @Json(name = "name")
        val name: Name? = null,
        @Json(name = "enterprise_extension")
        val enterpriseExtension: EnterpriseExtension? = null,
    )

@JsonClass(generateAdapter = true)
public data class SCIMConnection
    @JvmOverloads
    constructor(
        /**
         * Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations
         * on an Organization, so be sure to preserve this value. You may also use the organization_slug or
         * organization_external_id here as a convenience.
         */
        @Json(name = "organization_id")
        val organizationId: String,
        /**
         * The ID of the SCIM connection.
         */
        @Json(name = "connection_id")
        val connectionId: String,
        /**
         * The status of the connection. The possible values are deleted or active.
         */
        @Json(name = "status")
        val status: String,
        /**
         * A human-readable display name for the connection.
         */
        @Json(name = "display_name")
        val displayName: String,
        /**
         * Name of the IdP. Enum with possible values: `okta`, `microsoft-entra`, `cyberark`, `jumpcloud`, `onelogin`,
         * `pingfederate`, `rippling` or `generic`.
         *
         * Specifying a known provider allows Stytch to handle any provider-specific logic, such as automatically appending
         * `?aadOptscim062020` to the returned BaseURL for `microsoft-entra` SCIM Connections to
         * [enable the SCIM 2.0 compliant flag](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility#scim-20-compliance-issues-and-status).
         */
        @Json(name = "identity_provider")
        val identityProvider: String,
        /**
         * The URL supplied to the Identity Provider (IdP) alongside the bearer token enabling access to Stytch's SCIM API
         * endpoints
         */
        @Json(name = "base_url")
        val baseURL: String,
        /**
         * The last four digits of the bearer token. If you've lost access to your `bearer_token` and need to generate a new one,
         * use the [SCIM rotate token start endpoint](https://stytch.com/docs/b2b/api/scim-rotate-token-start).
         */
        @Json(name = "bearer_token_last_four")
        val bearerTokenLastFour: String,
        /**
         * An array of SCIM group implicit role assignments. Each object in the array must contain a `group_id` and a `role_id`.
         */
        @Json(name = "scim_group_implicit_role_assignments")
        val scimGroupImplicitRoleAssignments: List<SCIMGroupImplicitRoleAssignments>,
        @Json(name = "next_bearer_token_last_four")
        val nextBearerTokenLastFour: String,
        /**
         * The bearer token expiry time.
         */
        @Json(name = "bearer_token_expires_at")
        val bearerTokenExpiresAt: Instant? = null,
        /**
         * This field is supplied only during [token rotation](https://stytch.com/docs/b2b/api/scim-rotate-token-start). The next
         * bearer token expiry time.
         */
        @Json(name = "next_bearer_token_expires_at")
        val nextBearerTokenExpiresAt: Instant? = null,
    )

@JsonClass(generateAdapter = true)
public data class SCIMConnectionWithNextToken
    @JvmOverloads
    constructor(
        /**
         * Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations
         * on an Organization, so be sure to preserve this value. You may also use the organization_slug or
         * organization_external_id here as a convenience.
         */
        @Json(name = "organization_id")
        val organizationId: String,
        /**
         * The ID of the SCIM connection.
         */
        @Json(name = "connection_id")
        val connectionId: String,
        /**
         * The status of the connection. The possible values are deleted or active.
         */
        @Json(name = "status")
        val status: String,
        /**
         * A human-readable display name for the connection.
         */
        @Json(name = "display_name")
        val displayName: String,
        /**
         * The URL supplied to the Identity Provider (IdP) alongside the bearer token enabling access to Stytch's SCIM API
         * endpoints
         */
        @Json(name = "base_url")
        val baseURL: String,
        /**
         * Name of the IdP. Enum with possible values: `okta`, `microsoft-entra`, `cyberark`, `jumpcloud`, `onelogin`,
         * `pingfederate`, `rippling` or `generic`.
         *
         * Specifying a known provider allows Stytch to handle any provider-specific logic, such as automatically appending
         * `?aadOptscim062020` to the returned BaseURL for `microsoft-entra` SCIM Connections to
         * [enable the SCIM 2.0 compliant flag](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility#scim-20-compliance-issues-and-status).
         */
        @Json(name = "identity_provider")
        val identityProvider: String,
        /**
         * The last four digits of the bearer token. If you've lost access to your `bearer_token` and need to generate a new one,
         * use the [SCIM rotate token start endpoint](https://stytch.com/docs/b2b/api/scim-rotate-token-start).
         */
        @Json(name = "bearer_token_last_four")
        val bearerTokenLastFour: String,
        /**
         * This field is supplied only during [token rotation](https://stytch.com/docs/b2b/api/scim-rotate-token-start). This
         * token should be used as the new bearer token for the SCIM connection after token rotation has been completed using the
         * [SCIM rotate token complete endpoint](https://stytch.com/docs/b2b/api/scim-rotate-token-complete).
         */
        @Json(name = "next_bearer_token")
        val nextBearerToken: String,
        /**
         * An array of SCIM group implicit role assignments. Each object in the array must contain a `group_id` and a `role_id`.
         */
        @Json(name = "scim_group_implicit_role_assignments")
        val scimGroupImplicitRoleAssignments: List<SCIMGroupImplicitRoleAssignments>,
        /**
         * The bearer token expiry time.
         */
        @Json(name = "bearer_token_expires_at")
        val bearerTokenExpiresAt: Instant? = null,
        /**
         * This field is supplied only during [token rotation](https://stytch.com/docs/b2b/api/scim-rotate-token-start). The next
         * bearer token expiry time.
         */
        @Json(name = "next_bearer_token_expires_at")
        val nextBearerTokenExpiresAt: Instant? = null,
    )

@JsonClass(generateAdapter = true)
public data class SCIMConnectionWithToken
    @JvmOverloads
    constructor(
        /**
         * Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations
         * on an Organization, so be sure to preserve this value. You may also use the organization_slug or
         * organization_external_id here as a convenience.
         */
        @Json(name = "organization_id")
        val organizationId: String,
        /**
         * The ID of the SCIM connection.
         */
        @Json(name = "connection_id")
        val connectionId: String,
        /**
         * The status of the connection. The possible values are deleted or active.
         */
        @Json(name = "status")
        val status: String,
        /**
         * A human-readable display name for the connection.
         */
        @Json(name = "display_name")
        val displayName: String,
        /**
         * Name of the IdP. Enum with possible values: `okta`, `microsoft-entra`, `cyberark`, `jumpcloud`, `onelogin`,
         * `pingfederate`, `rippling` or `generic`.
         *
         * Specifying a known provider allows Stytch to handle any provider-specific logic, such as automatically appending
         * `?aadOptscim062020` to the returned BaseURL for `microsoft-entra` SCIM Connections to
         * [enable the SCIM 2.0 compliant flag](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility#scim-20-compliance-issues-and-status).
         */
        @Json(name = "identity_provider")
        val identityProvider: String,
        /**
         * The URL supplied to the Identity Provider (IdP) alongside the bearer token enabling access to Stytch's SCIM API
         * endpoints
         */
        @Json(name = "base_url")
        val baseURL: String,
        /**
         * The token supplied to the Identity Provider (IdP) alongside the base URL that grants access to Stytch's SCIM API
         * endpoints. It should be included in HTTP authorization headers. This field is supplied only on creation of the SCIM
         * connection.
         */
        @Json(name = "bearer_token")
        val bearerToken: String,
        /**
         * An array of SCIM group implicit role assignments. Each object in the array must contain a `group_id` and a `role_id`.
         */
        @Json(name = "scim_group_implicit_role_assignments")
        val scimGroupImplicitRoleAssignments: List<SCIMGroupImplicitRoleAssignments>,
        /**
         * The bearer token expiry time.
         */
        @Json(name = "bearer_token_expires_at")
        val bearerTokenExpiresAt: Instant? = null,
    )

@JsonClass(generateAdapter = true)
public data class SCIMGroup
    @JvmOverloads
    constructor(
        /**
         * Stytch-issued, globally unique UUID that identifies a specific SCIM Group. The entity `id` in the SCIM specification is
         * issued by the Service Provider (SP) and returned to the Identity Provider (IdP) to store and use for uniquely identify
         * and updating the Group moving forward.
         */
        @Json(name = "group_id")
        val groupId: String,
        /**
         * The displayName of the SCIM group, sent from the Identity Provider (IdP).
         */
        @Json(name = "group_name")
        val groupName: String,
        /**
         * Globally unique UUID that identifies a specific Organization. The organization_id is critical to perform operations on
         * an Organization, so be sure to preserve this value.
         */
        @Json(name = "organization_id")
        val organizationId: String,
        /**
         * The ID of the SCIM connection.
         */
        @Json(name = "connection_id")
        val connectionId: String,
    )

@JsonClass(generateAdapter = true)
public data class SCIMGroupImplicitRoleAssignments
    @JvmOverloads
    constructor(
        /**
         * The ID of the role.
         */
        @Json(name = "role_id")
        val roleId: String,
        /**
         * The ID of the group.
         */
        @Json(name = "group_id")
        val groupId: String,
        @Json(name = "group_name")
        val groupName: String,
    )

@JsonClass(generateAdapter = true)
public data class X509Certificate
    @JvmOverloads
    constructor(
        @Json(name = "value")
        val value: String,
        @Json(name = "type")
        val type: String,
        @Json(name = "primary")
        val primary: Boolean,
    )
