package com.stytch.java.consumer.api.fraudemail

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import com.squareup.moshi.Moshi
import com.stytch.java.common.InstantAdapter
import com.stytch.java.common.StytchResult
import com.stytch.java.consumer.models.fraudemail.RiskRequest
import com.stytch.java.consumer.models.fraudemail.RiskResponse
import com.stytch.java.http.HttpClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.future.asCompletableFuture
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.concurrent.CompletableFuture

public interface Email {
    /**
     * Get risk information for a specific email address.
     * The response will contain a recommended action (`ALLOW`, `BLOCK`, or `CHALLENGE`) and a more granular `risk_score`.
     * You can also check the `address_information` and `domain_information` fields for more information about the email
     * address and email domain.
     *
     * This feature is in beta. Reach out to us [here](mailto:fraud-team@stytch.com?subject=Email_Intelligence_Early_Access)
     * if you'd like to request early access.
     */
    public suspend fun risk(data: RiskRequest): StytchResult<RiskResponse>

    /**
     * Get risk information for a specific email address.
     * The response will contain a recommended action (`ALLOW`, `BLOCK`, or `CHALLENGE`) and a more granular `risk_score`.
     * You can also check the `address_information` and `domain_information` fields for more information about the email
     * address and email domain.
     *
     * This feature is in beta. Reach out to us [here](mailto:fraud-team@stytch.com?subject=Email_Intelligence_Early_Access)
     * if you'd like to request early access.
     */
    public fun risk(
        data: RiskRequest,
        callback: (StytchResult<RiskResponse>) -> Unit,
    )

    /**
     * Get risk information for a specific email address.
     * The response will contain a recommended action (`ALLOW`, `BLOCK`, or `CHALLENGE`) and a more granular `risk_score`.
     * You can also check the `address_information` and `domain_information` fields for more information about the email
     * address and email domain.
     *
     * This feature is in beta. Reach out to us [here](mailto:fraud-team@stytch.com?subject=Email_Intelligence_Early_Access)
     * if you'd like to request early access.
     */
    public fun riskCompletable(data: RiskRequest): CompletableFuture<StytchResult<RiskResponse>>
}

internal class EmailImpl(
    private val httpClient: HttpClient,
    private val coroutineScope: CoroutineScope,
) : Email {
    private val moshi = Moshi.Builder().add(InstantAdapter()).build()

    override suspend fun risk(data: RiskRequest): StytchResult<RiskResponse> =
        withContext(Dispatchers.IO) {
            var headers = emptyMap<String, String>()

            val asJson = moshi.adapter(RiskRequest::class.java).toJson(data)
            httpClient.post("/v1/email/risk", asJson, headers)
        }

    override fun risk(
        data: RiskRequest,
        callback: (StytchResult<RiskResponse>) -> Unit,
    ) {
        coroutineScope.launch {
            callback(risk(data))
        }
    }

    override fun riskCompletable(data: RiskRequest): CompletableFuture<StytchResult<RiskResponse>> =
        coroutineScope.async {
            risk(data)
        }.asCompletableFuture()
}
