package com.stytch.java.b2b.models.totpsv1b2b

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.stytch.java.b2b.models.organizations.Member
import com.stytch.java.b2b.models.organizations.Organization

@JsonClass(generateAdapter = true)
public data class CreateRequest
    @JvmOverloads
    constructor(
        @Json(name = "organization_id")
        val organizationId: String,
        @Json(name = "member_id")
        val memberId: String,
        @Json(name = "expiration_minutes")
        val expirationMinutes: Int? = null,
    )

@JsonClass(generateAdapter = true)
public data class CreateResponse
    @JvmOverloads
    constructor(
        @Json(name = "request_id")
        val requestId: String,
        @Json(name = "member_id")
        val memberId: String,
        @Json(name = "totp_registration_id")
        val totpRegistrationId: String,
        @Json(name = "secret")
        val secret: String,
        @Json(name = "qr_code")
        val qrCode: String,
        @Json(name = "recovery_codes")
        val recoveryCodes: List<String>,
        @Json(name = "member")
        val member: Member,
        @Json(name = "organization")
        val organization: Organization,
        @Json(name = "status_code")
        val statusCode: Int,
    )
