package com.stytch.java.consumer.models.devicehistory

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.Instant

@JsonClass(generateAdapter = true)
public data class DeviceAttributeDetails
    @JvmOverloads
    constructor(
        /**
         * Whether this `ip_geo_country` has been seen before for this user.
         */
        @Json(name = "is_new")
        val isNew: Boolean,
        /**
         * When this `ip_geo_country` was first seen for this user. Values conform to the RFC 3339 standard and are expressed in
         * UTC, e.g. `2021-12-29T12:33:09Z`.
         */
        @Json(name = "first_seen_at")
        val firstSeenAt: Instant? = null,
        /**
         * When this `ip_geo_country` was last seen for this user. Values conform to the RFC 3339 standard and are expressed in
         * UTC, e.g. `2021-12-29T12:33:09Z`.
         */
        @Json(name = "last_seen_at")
        val lastSeenAt: Instant? = null,
    )

@JsonClass(generateAdapter = true)
public data class DeviceInfo
    @JvmOverloads
    constructor(
        /**
         * The `visitor_id` (a unique identifier) of the user's device. See the
         * [Device Fingerprinting documentation](https://stytch.com/docs/fraud/guides/device-fingerprinting/fingerprints) for more
         * details on the `visitor_id`.
         */
        @Json(name = "visitor_id")
        val visitorId: String,
        /**
         * Information about the `visitor_id`.
         */
        @Json(name = "visitor_id_details")
        val visitorIdDetails: DeviceAttributeDetails? = null,
        /**
         * The IP address of the user's device.
         */
        @Json(name = "ip_address")
        val ipAddress: String? = null,
        /**
         * Information about the `ip_address`.
         */
        @Json(name = "ip_address_details")
        val ipAddressDetails: DeviceAttributeDetails? = null,
        /**
         * The city where the IP address is located.
         */
        @Json(name = "ip_geo_city")
        val ipGeoCity: String? = null,
        /**
         * The region where the IP address is located.
         */
        @Json(name = "ip_geo_region")
        val ipGeoRegion: String? = null,
        /**
         * The country code where the IP address is located.
         */
        @Json(name = "ip_geo_country")
        val ipGeoCountry: String? = null,
        /**
         * Information about the `ip_geo_country`.
         */
        @Json(name = "ip_geo_country_details")
        val ipGeoCountryDetails: DeviceAttributeDetails? = null,
    )
