on:
  push:
    branches: [ "master" ]
  workflow_dispatch: { }

env:
  version: 8.0.${{ github.run_number }}

jobs:
  publish:
    runs-on: hetzner-runner
    container:
      image: 588738576859.dkr.ecr.eu-west-1.amazonaws.com/paradym-ci:latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ env.version }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ env.version }}" \
              --generate-notes

      - name: Publish
        env:
          GITHUB_ACTOR: "github"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: ./gradlew build publish -Pversion=${{ env.version }}
